# Test funtion code

In [1]:
from HW3_utils import FKHW3

In [2]:
R,P,R_e,p_e = FKHW3([0,0,0])

In [3]:
print(f'R : {R}\nP : {P}\nR_e : {R_e}\np_e : {p_e}')

R : [[[-1.0000000e+00 -1.0000000e+00 -1.0000000e+00  6.1232343e-17]
  [-1.2246469e-16 -7.4987988e-33 -7.4987988e-33  6.1232343e-17]
  [ 0.0000000e+00  1.2246469e-16  1.2246469e-16  1.0000000e+00]]

 [[ 1.2246469e-16  1.2246469e-16  1.2246469e-16  1.0000000e+00]
  [-1.0000000e+00 -6.1232343e-17 -6.1232343e-17 -1.2246469e-16]
  [ 0.0000000e+00  1.0000000e+00  1.0000000e+00 -6.1232343e-17]]

 [[ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.2246469e-16]
  [ 0.0000000e+00  1.0000000e+00  1.0000000e+00  1.0000000e+00]
  [ 1.0000000e+00  6.1232343e-17  6.1232343e-17 -6.1232343e-17]]]
P : [[ 0.0000000e+00  0.0000000e+00  4.2500000e-01  8.9943000e-01]
 [ 0.0000000e+00  0.0000000e+00 -5.2047489e-17  1.0900000e-01]
 [ 8.9200000e-02  8.9200000e-02  8.9200000e-02 -3.8000000e-03]]
R_e : [[ 6.1232343e-17  6.1232343e-17  1.0000000e+00]
 [ 1.0000000e+00 -1.2246469e-16 -6.1232343e-17]
 [ 1.2246469e-16  1.0000000e+00 -6.1232343e-17]]
p_e : [ 0.89943  0.109   -0.0038 ]


## ข้อ 1

In [4]:
import numpy as np

In [5]:
J_v = np.empty((3, 3))
J_w = np.empty((3, 3))

In [6]:
for i in range(3):
    r = np.dot(R[:,:,i],[[0],[0],[1]])
    d = p_e - P[:,i]
    r = r.reshape(3,)

    j_trans = np.cross(r,d)

    print(f'------J_{i}------\n{j_trans}')
    print(f'------R_{i}------\n{r}')

    J_v[0][i] = j_trans[0]
    J_v[1][i] = j_trans[1]
    J_v[2][i] = j_trans[2]

    J_w[0][i] = r[0]
    J_w[1][i] = r[1]
    J_w[2][i] = r[2]


------J_0------
[-0.109    0.89943  0.     ]
------R_0------
[0. 0. 1.]
------J_1------
[-9.30000000e-02  6.64634217e-17 -8.99430000e-01]
------R_1------
[1.22464685e-16 1.00000000e+00 6.12323426e-17]
------J_2------
[-9.3000000e-02  4.0439676e-17 -4.7443000e-01]
------R_2------
[1.22464685e-16 1.00000000e+00 6.12323426e-17]


In [7]:
J = np.concatenate((J_v, J_w), axis=0)
J

array([[-1.09000000e-01, -9.30000000e-02, -9.30000000e-02],
       [ 8.99430000e-01,  6.64634217e-17,  4.04396760e-17],
       [ 0.00000000e+00, -8.99430000e-01, -4.74430000e-01],
       [ 0.00000000e+00,  1.22464685e-16,  1.22464685e-16],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  6.12323426e-17,  6.12323426e-17]])

## ข้อ 2

In [8]:
e = 0.001

In [9]:
J_reduce = J[:3, :3]
J_reduce

array([[-1.09000000e-01, -9.30000000e-02, -9.30000000e-02],
       [ 8.99430000e-01,  6.64634217e-17,  4.04396760e-17],
       [ 0.00000000e+00, -8.99430000e-01, -4.74430000e-01]])

In [10]:
m = np.linalg.det(J_reduce)
m

0.03554997075000001

In [11]:
if m < e :
    print('Singularity')
else:
    print('Not Singularity')

Not Singularity


## ข้อ 3

In [12]:
w = np.array([1 ,2 ,3 ,4 ,5 ,6])

In [13]:
w = w.reshape(6,1)

In [14]:
w_f = w[3:, :]

In [15]:
w_f

array([[4],
       [5],
       [6]])

In [16]:
t = np.dot(J_reduce,w_f)

In [17]:
t

array([[-1.459  ],
       [ 3.59772],
       [-7.34373]])

# Call funtion

In [18]:
from FRA333_HW3_6512_6550 import endEffectorJacobianHW3 , checkSingularityHW3 , computeEffortHW3

In [19]:
q = [1 ,2 ,3]
w = [1 ,2 ,3 ,4 ,5 ,6]

In [20]:
J_e = endEffectorJacobianHW3(q)
J_e

array([[-9.83540720e-02,  2.27523742e-02,  2.31552949e-01],
       [-6.63826432e-02,  3.54347240e-02,  3.60622359e-01],
       [ 0.00000000e+00, -4.68954018e-02, -2.23757800e-01],
       [ 0.00000000e+00, -8.41470957e-01, -8.41470957e-01],
       [ 0.00000000e+00,  5.40302277e-01,  5.40302277e-01],
       [ 1.00000000e+00,  6.12323426e-17,  6.12323426e-17]])

In [21]:
flag = checkSingularityHW3(q)
flag

True

In [22]:
tau = computeEffortHW3(q,w)
tau

array([[ 1.10966328],
       [ 2.0753772 ],
       [-1.57702381]])