In [1]:
from HW3_utils import FKHW3

In [2]:
R,P,R_e,p_e = FKHW3([0,0,0])

In [3]:
print(f'R : {R}\nP : {P}\nR_e : {R_e}\np_e : {p_e}')

R : [[[-1.0000000e+00 -1.0000000e+00 -1.0000000e+00  6.1232343e-17]
  [-1.2246469e-16 -7.4987988e-33 -7.4987988e-33  6.1232343e-17]
  [ 0.0000000e+00  1.2246469e-16  1.2246469e-16  1.0000000e+00]]

 [[ 1.2246469e-16  1.2246469e-16  1.2246469e-16  1.0000000e+00]
  [-1.0000000e+00 -6.1232343e-17 -6.1232343e-17 -1.2246469e-16]
  [ 0.0000000e+00  1.0000000e+00  1.0000000e+00 -6.1232343e-17]]

 [[ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.2246469e-16]
  [ 0.0000000e+00  1.0000000e+00  1.0000000e+00  1.0000000e+00]
  [ 1.0000000e+00  6.1232343e-17  6.1232343e-17 -6.1232343e-17]]]
P : [[ 0.0000000e+00  0.0000000e+00  4.2500000e-01  8.9943000e-01]
 [ 0.0000000e+00  0.0000000e+00 -5.2047489e-17  1.0900000e-01]
 [ 8.9200000e-02  8.9200000e-02  8.9200000e-02 -3.8000000e-03]]
R_e : [[ 6.1232343e-17  6.1232343e-17  1.0000000e+00]
 [ 1.0000000e+00 -1.2246469e-16 -6.1232343e-17]
 [ 1.2246469e-16  1.0000000e+00 -6.1232343e-17]]
p_e : [ 0.89943  0.109   -0.0038 ]


### ข้อ 1

In [4]:
import numpy as np

In [5]:
J_v = np.empty((3, 3))
J_w = np.empty((3, 3))

In [6]:
for i in range(3):
    r = np.dot(R[:,:,i],[[0],[0],[1]])
    d = p_e - P[:,i]
    r = r.reshape(3,)

    j_trans = np.cross(r,d) + np.dot(R_e,p_e)

    print(f'------J_{i}------\n{j_trans}')
    print(f'------R_{i}------\n{r}')

    J_v[0][i] = j_trans[0]
    J_v[1][i] = j_trans[1]
    J_v[2][i] = j_trans[2]

    J_w[0][i] = r[0]
    J_w[1][i] = r[1]
    J_w[2][i] = r[2]


------J_0------
[-0.1128   1.79886  0.109  ]
------R_0------
[0. 0. 1.]
------J_1------
[-0.0968   0.89943 -0.79043]
------R_1------
[1.22464685e-16 1.00000000e+00 6.12323426e-17]
------J_2------
[-0.0968   0.89943 -0.36543]
------R_2------
[1.22464685e-16 1.00000000e+00 6.12323426e-17]


In [7]:
J = np.concatenate((J_v, J_w), axis=0)
J

array([[-1.12800000e-01, -9.68000000e-02, -9.68000000e-02],
       [ 1.79886000e+00,  8.99430000e-01,  8.99430000e-01],
       [ 1.09000000e-01, -7.90430000e-01, -3.65430000e-01],
       [ 0.00000000e+00,  1.22464685e-16,  1.22464685e-16],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  6.12323426e-17,  6.12323426e-17]])

### ข้อ 2

In [8]:
e = 0.001

In [9]:
J_reduce = J[:3, :3]
J_reduce

array([[-0.1128 , -0.0968 , -0.0968 ],
       [ 1.79886,  0.89943,  0.89943],
       [ 0.109  , -0.79043, -0.36543]])

In [10]:
m = np.linalg.det(J_reduce)
m

0.03088642620000005

In [11]:
if m < e :
    print('Singularity')
else:
    print('Not Singularity')

Not Singularity


### ข้อ 3

In [52]:
w = np.array([1 ,2 ,3 ,4 ,5 ,6])

In [53]:
w = w.reshape(6,1)

In [54]:
w_f = w[:3, :]

In [55]:
w_f

array([[1],
       [2],
       [3]])

In [56]:
t = np.dot(J_reduce,w_f)

In [57]:
t

array([[-0.5968 ],
       [ 6.29601],
       [-2.56815]])